# Generated by Django 3.2.7 on 2021-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseworks',
            name='point',
            field=models.IntegerField(default=0, null=True, verbose_name='ポイント'),
        ),
    ]
