# Generated by Django 3.2.7 on 2021-10-14 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0002_alter_houseworks_point'),
        ('help_app', '0002_auto_20211006_2153'),
    ]

    operations = [
    ]
