# Generated by Django 3.2.7 on 2021-10-09 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0002_alter_houseworks_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='icon',
        ),
    ]
