# Generated by Django 3.2.7 on 2021-10-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0003_alter_days_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='tag',
            field=models.CharField(default='id_name', max_length=255, unique=True, verbose_name='id名'),
        ),
    ]
