# Generated by Django 3.2.7 on 2021-10-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_app', '0004_tasks_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='tag',
        ),
    ]
